name: Get Unity license activation file ğŸ”

on: workflow_dispatch

jobs:
    checkLicense:
        name: Check for Unity license
        runs-on: ubuntu-latest
        steps:
            -name: Fail - No license
            if: ${{ !startWith(env.UNITY_LICENSEm'<') }}
            run: exit 1
  requestManualActivationFile:
    needs: checkLicense
    name: Request manual activation file ğŸ”‘
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: game-ci/unity-request-activation-file@v2
        id: getManualLicenseFile

      - uses: actions/upload-artifact@v2
        with:
          name: Manual Activation File
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}
